[spotify]
# Run natively on wayland
extra_arguments = ["--enable-features=UseOzonePlatform", "--ozone-platform=wayland"]
# Status on 18.4.2026, the most recent Spotify version ignores --ozone-platform when DISPLAY env variable is set
# so unsetting it here... https://github.com/kpcyrd/spotify-launcher/issues/108
# Probably fixed in some future release
extra_env_vars = ["DISPLAY="]