- name: Install pacman packages
  hosts: localhost

  tasks:
      - name: Pacman base packages
        become: true
        community.general.pacman:
            package:
                - zsh
                - wireguard-tools
                - ansible-core
                - ansible-lint
                - ansible
                - syncthing
                - python-pexpect
                - zip
                - unzip
                - inotify-tools
                - android-tools
                - wl-clipboard
                - imv
                - vlc
