- name: Install and enable bluetooth
  hosts: localhost

  tasks:
    - name: Install bluez
      become: true
      community.general.pacman:
        package:
          - bluez
          - bluez-utils
          - bluetui

    - name: Enable bluetooth service
      become: true
      ansible.builtin.systemd:
        service: bluetooth.service
        state: started
        enabled: true
