- name: Install Docker
  hosts: localhost

  tasks:
      - name: Install pacman packages
        become: true
        community.general.pacman:
            package:
                - docker
                - docker-buildx

      - name: Enable Docker service socket
        become: true
        ansible.builtin.systemd_service:
            name: docker.socket
            enabled: true

      - name: Add current user to docker group
        become: true
        ansible.builtin.user:
            name: "{{ ansible_user_id }}"
            groups: docker
            append: true
