- name: Configure wireless networking
  hosts: localhost

  vars:
      laptop_hostnames: ["rend"]

  tasks:
      - name: Install iwd
        when: ansible_hostname in laptop_hostnames
        become: true
        community.general.pacman:
            package:
                - iwd

      - name: Set NetworManager backend to iwd
        when: ansible_hostname in laptop_hostnames
        become: true
        ansible.builtin.copy:
            dest: /etc/NetworkManager/conf.d/iwd.conf
            content: |
                [device]
                wifi.backend=iwd
            mode: u=rw

      - name: Stop NetworManager
        when: ansible_hostname in laptop_hostnames
        become: true
        ansible.builtin.systemd:
            service: NetworManager
            state: stopped

      - name: Disable wpa_supplicant
        when: ansible_hostname in laptop_hostnames
        become: true
        ansible.builtin.systemd:
            service: wpa_supplicant
            state: stopped
            enabled: false

      - name: Start NetworManager
        when: ansible_hostname in laptop_hostnames
        become: true
        ansible.builtin.systemd:
            service: NetworManager
            state: started
