- name: Run all installation playbooks
  hosts: localhost

- name: Generate playbook collection
  ansible.builtin.import_playbook: generated/generate.yml

- name: Run playbooks in order
  ansible.builtin.import_playbook: generated/all_ordered.yml
